'use client';

// Audio Analyst: narrates the model's read of the game using the browser's own
// speech synthesis. The narration text is buildCommentary output, i.e. entirely
// derived from play-by-play and the model; export downloads the same text.

import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react';
import { buildCommentary } from '@/lib/model/shimi';
import type { GameData } from '@/lib/types';

const noSubscribe = () => () => {};

export default function AudioAnalyst({ game, series }: { game: GameData; series: number[] }) {
  const [speaking, setSpeaking] = useState(false);
  // browser capability, read once on the client; server assumes supported
  const supported = useSyncExternalStore(noSubscribe, () => 'speechSynthesis' in window, () => true);
  const utterRef = useRef<SpeechSynthesisUtterance | null>(null);

  const commentary = useMemo(() => buildCommentary(game, series), [game, series]);

  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) window.speechSynthesis.cancel();
    };
  }, []);

  const toggle = () => {
    if (!supported) return;
    if (speaking) {
      window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }
    const u = new SpeechSynthesisUtterance(commentary);
    u.rate = 1.02;
    u.onend = () => setSpeaking(false);
    u.onerror = () => setSpeaking(false);
    utterRef.current = u;
    window.speechSynthesis.speak(u);
    setSpeaking(true);
  };

  const exportTxt = () => {
    const blob = new Blob([commentary + '\n\nGenerated by Shimi, HoopsAi. Model output, not betting advice.'], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `hoopsai_commentary_${game.away.abbrev}_at_${game.home.abbrev}.txt`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="panel p-4">
      <div className="label mb-2 flex items-center gap-2">
        <span>🎙</span> Audio analyst
      </div>
      <p className="text-[11px] text-muted mb-3 leading-relaxed">Narrative voiceover of game dynamics and momentum shifts, straight from the model.</p>
      <div className="flex gap-2">
        <button className="btn flex-1" onClick={toggle} disabled={!supported} title={supported ? '' : 'Speech synthesis is not available in this browser'}>
          {speaking ? '■ Stop' : '▶ Narrate'}
        </button>
        <button className="btn flex-1" onClick={exportTxt}>
          Export commentary
        </button>
      </div>
    </div>
  );
}
